version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects
hooks:
  #  BeforeInstall:
  #    - location: /home/ubuntu/projects/scripts/prepare.sh
  #    - location: Scripts/UnzipDataBundle.sh
  AfterInstall:
    - location: /home/ubuntu/projects/scripts/prepare.sh
#      timeout: 180
#  ApplicationStart:
#    - location: Scripts/RunFunctionalTests.sh
#      timeout: 3600
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600
#      runas: codedeployuser
#
