version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: ec2-user
