version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: /home/ubuntu/projects/init.sh
      runas: ubuntu
