version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  Install:
    - location: scripts/start.sh
      runas: ubuntu
