version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: stop.sh
    - runas: ubuntu
#  ApplicationStart:
#    - location: init.sh
#      runas: ubuntu
