version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: stop.sh
    - runas: ubuntu
  Install:
    - location: init.sh
      runas: ubuntu
