version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects

hooks:
  ApplicationStop:
    - location: stop.sh
    - runas: ubuntu
    - timeout: 300

  ApplicationStart:
    - location: init.sh
    - runas: ubuntu
    - timeout: 300

  BeforeInstall:
    - location: before.sh
    - runas: ubuntu
    - timeout: 300
